export const siteConfig = {
  name: "Jatin Sharma - Full Stack Developer",
  authorName: "Jatin Sharma",
  username: "Jatin",
  description:
    "Full-stack developer building scalable, high-performance web applications from idea to deployment with clean architecture and modern technologies.",
  url: "https://nbarkiya.xyz/",
  links: {
    twitter: "https://x.com/nitaj333",
    github: "https://github.com/iamj3",
    templateRepo: "https://github.com/iamj3/portfolio",
  },
  keywords: [
    "Jatin Sharma",
    "Full Stack Developer",
    "Software Engineer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React.js Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
